import type { Metadata } from "next";
import { poppins, openSans, breathing } from "./fonts";
import Footer from "@/components/Footer"

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" className={`${poppins.variable} ${openSans.variable} ${breathing.variable}`}>
      <body>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
